package id.ac.poliban.listligainggris;

import java.util.ArrayList;
import java.util.List;

public class LigaInggrisData {
    static List<LigaInggris> getAllClub(){
        List<LigaInggris> data = new ArrayList<>();
        {
            data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/7/7a/Manchester_United_FC_crest.svg/220px-Manchester_United_FC_crest.svg.png", "Manchester United", "Manchester United Football Club adalah sebuah klub sepak bola profesional Inggris yang berbasis di Old Trafford, Manchester Raya, yang bermain di Liga Inggris. Didirikan sebagai Newton Heath LYR Football Club pada tahun 1878, klub ini berganti nama menjadi Manchester United pada 1902 dan pindah ke Old Trafford pada tahun 1910."));
            data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/5/53/Arsenal_FC.svg/180px-Arsenal_FC.svg.png", "Arsenal", "Arsenal Football Club (dikenal pula sebagai Arsenal atau The Gunners) adalah klub sepak bola profesional Inggris yang berbasis di daerah Holloway, London. didirikan pada 1886 dengan nama Dial Square. Klub ini bermain di Liga Utama Inggris yang termasuk salah satu klub tersukses di sepak bola Inggris, yang telah memenangkan 13 gelar kasta utama Liga Inggris (10 pada era Divisi Pertama dan 3 pada era Premier League) dan 13 gelar di Piala FA (Gelar paling banyak)."));
            data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/c/cc/Chelsea_FC.svg/200px-Chelsea_FC.svg.png", "Chelsea", "Chelsea Football Club /'t??lsi?/ adalah sebuah klub sepak bola Inggris yang bermarkas di Fulham, London. Chelsea didirikan pada tahun 1905 dan kini berkompetisi di Liga Utama Inggris."));
            data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/6/6c/Leicester_FC_Logo.svg/200px-Leicester_FC_Logo.svg.png", "Leicester City", "Leicester City F.C. adalah sebuah tim sepak bola Inggris berbasis di Leicester. Leicester Dikenal juga dengan sebutan The Foxes. Klub ini memainkan pertandingan kandangnya di Stadion King Power yang berkapsitas 32.000 penonton."));
            data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/e/eb/Manchester_City_FC_badge.svg/200px-Manchester_City_FC_badge.svg.png", "Manchester City", "Manchester City Football Club (dikenal pula sebagai Man City atau The Citizens) adalah sebuah klub sepak bola profesional dari Inggris yang bermain di Liga Premier Inggris. Klub ini merupakaan klub sekota dengan Manchester United dan bermarkas di Stadion Etihad, Manchester."));
            data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/0/0f/Blackburn_Rovers.svg/200px-Blackburn_Rovers.svg.png", "Blackburn Rovers", "Blackburn Rovers Football Club adalah sebuah tim sepak bola Inggris yang saat ini bermain di Liga Championship Inggris. Bermarkas di Blackburn, Inggris. Didirikan tahun 1875. dan pernah menjuarai liga utama inggris sebanyak 3 kali."));
            data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/0/0c/Liverpool_FC.svg/180px-Liverpool_FC.svg.png", "Liverpool", "Liverpool Football Club /'l?v?rpu?l/ (dikenal pula sebagai Liverpool atau The Reds) adalah sebuah klub sepak bola asal Inggris yang berbasis di Kota Liverpool. Saat ini Liverpool adalah peserta Liga Utama Inggris. Liverpool juga merupakan juara bertahan Liga Champions UEFA musim 2018-2019."));
            data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/f/fd/Brighton_%26_Hove_Albion_logo.svg/200px-Brighton_%26_Hove_Albion_logo.svg.png", "Brighton", "Brighton & Hove Albion Football Club adalah sebuah klub sepak bola profesional asal Inggris yang berbasis di kota pantai Brighton & Hove, di timur Sussex. Sering disebut sebagai Brighton & Hove Albion atau hanya sekadar sebagai Brighton. Saat ini bermain di Football League Championship, tingkat kedua dari sistem liga sepak bola Inggris, menggelar pertandingan di Stadion Falmer berpakasitas 30.750 penonton, yang dikenal dalam tujuan sponsor sebagai Stadion Komunitas American Express, atau singkatnya Amex.. Mereka akan menjalankan debut Liga Utama mereka di musim 2017-18 setelah menyegel promosi otomatis dari Kejuaraan EFL."));
            data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/f/f9/Aston_Villa_FC_crest_%282016%29.svg/150px-Aston_Villa_FC_crest_%282016%29.svg.png", "Aston Villa", "Aston Villa Football Club (/'æst?n 'v?ll?/; juga dikenal sebagai Villa, The Villa, The Villans dan The Lions)[5] adalah klub sepak bola profesional yang bermarkas di Villa Park, Birmingham, Inggris. Klub ini bermain di Liga Utama Inggris dan merupakan salah satu klub pendiri Liga Sepak Bola (Football League) pada tahun 1888 serta Liga Utama pada tahun 1992. Aston Villa merupakan salah satu klub tertua dan tersukses Inggris."));
            data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/c/c2/West_Ham_United_FC_logo.svg/200px-West_Ham_United_FC_logo.svg.png", "West Ham", "West Ham United Football Club adalah sebuah klub sepak bola Inggris yang bermarkas di London. Sejak 2016, klub ini memainkan pertandingan kandangnya di London Stadium yang berkapasitas 80.000 kursi. Sebelumnya Hammers bermain di Boleyn Ground. Seragam mereka berwarna merah-biru."));
        }
        return data;
    }
}